spring:
  application:
    name: QueueStormInvestigator
  config:
    import: optional:file:.env[.properties]
  jackson:
    default-property-inclusion: non_null

server:
  port: 8080

gemini:
  api:
    key: ${GEMINI_API_KEY:default_key}
